### USERS
GET http://localhost:3000/users


### REGISTER
POST http://localhost:3000/register
content-type: application/json

{
  "name": "Elder Ramos",
  "email": "elder1@pucminas.br",
  "password": "teste",
}

### LOGIN
PUT http://localhost:3000/users/3
content-type: application/json

{
  "tipo": 1,
  "data": "10/01/2022",
  "preco": 7.5,
  "valor": 130.00,
  "odometro": 34000
}


### GET GASTO
GET http://localhost:3000/users/3

### DELETE GASTO
DELETE http://localhost:3000/users/3
