### USERS
GET http://localhost:3000/users


### REGISTER
POST http://localhost:3000/register
content-type: application/json

{
  "name": "Elder Ramos",
  "email": "elder1@pucminas.br",
  "password": "teste",
}

### LOGIN
PUT http://localhost:3000/users/3
content-type: application/json

{
  "name": "Elder Ramos",
  "email": "elder1@pucminas.br",
  "password": "teste",
}



### GET USER
GET http://localhost:3000/users/3

### DELETE USER
DELETE http://localhost:3000/users/3
